version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb-1.8
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_FLUX_ENABLED=true
      - INFLUXDB_DB=testing
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=my-password
    network_mode: host
    tty: true
    stdin_open: true
    restart: unless-stopped
