version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: bitburner-nginx
    ports:
      - "80:80"
    volumes:
      - ./bitburner-official.github.io:/usr/share/nginx/html
    command: /bin/sh -c "apk add --no-cache git && git clone https://github.com/bitburner-official/bitburner-official.github.io /usr/share/nginx/html && nginx -g 'daemon off;'"
